# Generated by Django 4.2.2 on 2023-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Имя преподавателя')),
                ('desc', models.TextField(verbose_name='Имя преподавателя')),
                ('image', models.ImageField(upload_to='teachers', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'преподавателя',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
