# Generated by Django 4.2.2 on 2023-07-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonimentscards',
            name='dlina',
        ),
    ]
