# Generated by Django 4.2.2 on 2023-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image_mob',
            field=models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Моб картинка сайта'),
        ),
    ]
