# Generated by Django 4.2.2 on 2023-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_remove_abonimentscards_dlina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonimentscards',
            name='old_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abonimentscards',
            name='price',
            field=models.IntegerField(),
        ),
    ]
