# Generated by Django 4.2.2 on 2023-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_abonimentstitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonimentsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=120, verbose_name='Главный заголовок')),
                ('title2', models.CharField(max_length=120, verbose_name='Второй заголовок')),
                ('birka', models.CharField(max_length=120, verbose_name='Бирка')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('bonus', models.TextField(verbose_name='Бонус')),
                ('price', models.CharField(max_length=120, verbose_name='Цена')),
                ('button', models.CharField(max_length=120, verbose_name='Надпись кнопки')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'Абонементы. Редактировать',
            },
        ),
        migrations.AlterModelOptions(
            name='abonimentstitle',
            options={'verbose_name': 'заголовок', 'verbose_name_plural': 'Абонементы. Заголовки'},
        ),
        migrations.AlterModelOptions(
            name='page6session',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'Расписание. Редактировать'},
        ),
    ]
