# Generated by Django 4.2.2 on 2023-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_alter_abonimentscards_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP'),
        ),
    ]
