# Generated by Django 4.2.2 on 2023-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_page2slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Описание преимущества')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.AlterModelOptions(
            name='page2slider',
            options={'verbose_name': 'Заполнение карточки', 'verbose_name_plural': 'Второй экран 3 КАРТОЧКИ'},
        ),
    ]
