# Generated by Django 4.2.2 on 2023-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0004_abonimentscards_alter_abonimentstitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonimentscards',
            name='old_price',
            field=models.CharField(default=1, max_length=120, verbose_name='Старая цена'),
            preserve_default=False,
        ),
    ]
