# Generated by Django 4.2.2 on 2023-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0004_advantages_alter_page2slider_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page4Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Заголовок 1')),
                ('title2', models.CharField(max_length=50, verbose_name='Заголовок 2')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '4 экран',
                'verbose_name_plural': '4 экран',
            },
        ),
    ]
