# Generated by Django 4.2.2 on 2023-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0004_orders_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFormTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=150, verbose_name='Верхний заголовок')),
                ('title2', models.CharField(max_length=150, verbose_name='Нижний заголов')),
                ('desc', models.TextField(verbose_name='Описание предложения')),
                ('button', models.CharField(max_length=120, verbose_name='Надпись кнопки')),
            ],
            options={
                'verbose_name': 'бесплатную форму',
                'verbose_name_plural': 'Бесплатная форма',
            },
        ),
    ]
