# Generated by Django 4.2.2 on 2023-07-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0005_freeformtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
