# Generated by Django 4.2.2 on 2023-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0006_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lead', verbose_name='Изображение')),
                ('title1', models.CharField(max_length=120, verbose_name='Главный заголовок')),
                ('title2', models.CharField(max_length=120, verbose_name='Второй заголовок')),
                ('button', models.CharField(max_length=120, verbose_name='Надпись кнопки')),
            ],
            options={
                'verbose_name': 'параметр',
                'verbose_name_plural': 'Экран заявка',
            },
        ),
    ]
