# Generated by Django 4.2.2 on 2023-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0007_leadpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Главный заголовок')),
                ('title2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Второй заголовок')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Вопросы. Заголовки',
            },
        ),
    ]
