# Generated by Django 4.2.2 on 2023-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0007_page5title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page5title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page5', verbose_name='Изображение'),
        ),
    ]
