# Generated by Django 4.2.2 on 2023-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0009_quests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
