# Generated by Django 4.2.2 on 2023-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0009_alter_page5title_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page5title',
            name='title2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Нижний заголовок'),
        ),
    ]
