# Generated by Django 4.2.2 on 2023-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0010_alter_page5title_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page5Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Главный заголовок')),
                ('title2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Нижний заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '5 экран карта',
                'verbose_name_plural': '5 экран карта',
            },
        ),
    ]
