# Generated by Django 4.2.2 on 2023-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0011_alter_contacts_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на телеграм'),
        ),
    ]
