# Generated by Django 4.2.2 on 2023-07-02 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телеграм клиента')),
                ('price', models.CharField(max_length=30, verbose_name='Стоимость')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='IP')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('source', models.TextField(blank=True, null=True, verbose_name='Источник')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время заказа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
