# Generated by Django 4.2.2 on 2023-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buy_chat',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Купленный чат'),
        ),
    ]
