# Generated by Django 4.2.2 on 2023-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_buy_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='buy_chat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Купленный чат'),
        ),
    ]
