# Generated by Django 4.2.2 on 2023-07-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tg', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID телеграма')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Полное имя')),
                ('login', models.CharField(blank=True, max_length=120, null=True, verbose_name='Логин')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Телефон')),
                ('join_date', models.DateField(default=datetime.datetime.now, verbose_name='Первый контакт')),
                ('last_time', models.DateField(blank=True, null=True, verbose_name='Последний')),
                ('push1', models.BooleanField(default=True)),
                ('push2', models.BooleanField(default=True)),
                ('rang', models.CharField(blank=True, max_length=120, null=True, verbose_name='Статус')),
                ('license', models.BooleanField(default=False, verbose_name='Лицензия')),
                ('start_license', models.DateField(blank=True, null=True, verbose_name='Начало лицензии')),
                ('ower_license', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('other', models.CharField(blank=True, max_length=120, null=True, verbose_name='Другое')),
                ('demo', models.BooleanField(default=False, verbose_name='Бесплатный доступ')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
