# Generated by Django 4.2.2 on 2023-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='buy_chat',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Купленный чат'),
        ),
        migrations.AlterField(
            model_name='users',
            name='demo',
            field=models.BooleanField(default=False, verbose_name='Free оффер'),
        ),
    ]
