# Generated by Django 4.2.2 on 2023-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='payment_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Платёжка'),
        ),
    ]
